name: Auto-Update-Causality

on:
  schedule:
    - cron: '0 16 * * 2,4,7' # 每周二、四、日自动运行
  workflow_dispatch:        # 这行保证你会看到那个手动运行的按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install requests pandas
      - name: Run Miner
        run: python update_data.py
      - name: Push Back
        run: |
          git config --global user.name "causality-bot"
          git config --global user.email "bot@antigravity.os"
          git add ssq_history_full.csv
          git commit -m "Auto-fix causality chain" || exit 0
          git push
